### ISSUE TITLE
Testing it but it doesnt compile with swift5

### ISSUE THREAD

**Issue by nferruzzi** [kkieffer/ALCameraViewController#1]
Looks like it is in the middle of a conversion, my clone (using pods) has swiff4 methods yet.
ie SendSubviewToBack
I've noticed there is a commit reverting back some changes that look like they are needed.

**Comment by nferruzzi** [comment]
nvm, xcode was wrong about the need for conversion, the problem is you still have SWIFT 4.0 in your podspec

**Comment by kkieffer** [comment]
Merged your pull request.
